server:
  port: 8020
spring:
  application:
    name: mdh-config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}	# 注册到consul的服务名称
    config:
      label: master  # git仓库分支
      server:
        git:
          uri: https://gitee.com/jansens/config.git  # 配置git仓库的地址
          search-paths: /config-repo  # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 2251478696@qq.com  # git仓库的账号
          password: Jansens@5201314  # git仓库的密码
management:
  endpoints:
    web:
      exposure:
        include: "*"